
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:LostPanda/ConfigRepo.git
          ignoreLocalSshSettings: true
          hostKey: someHostKey
          hostKeyAlgorithm: ssh-rsa
          privateKey: |
                      -----BEGIN RSA PRIVATE KEY-----
                      MIIEpQIBAAKCAQEAt7+btGSl2XDW1RWpJh+miHgY069yGRxZk/17MB+iF/jDQwFE
                      xrc+TNfJGdwFBnIAIgUBz8MrzCVTCz+s2i4ZGjuX7RBBY2wfmAO6QxRINf5kUEHF
                      mzpgwjQXxPkAOby2z8yvrNhqgToTFqs5dY5j6xfoB5HANhKArx/hGx+TWXyJZv4U
                      UxYZfbfqSLjlBOHyhA5Kx5zAC0aygI64fl2xVFeeJX0D89We3jGW62xk0FihwOrE
                      lVIKTqqQHmASAzP3XDErr5ZxP9VdpxZiiMraqUk+zHKf4F4kAM/6ZvUXZnjv5sfC
                      r31vnsXKVXNS0aYFrVluplmNiUkd3utSOvT6IQIDAQABAoIBAC6mwCJxt0XYh0K8
                      aCCcwow9aZg9IAvODdQr9B3Iuj+50eFuLgcBuRiLZKxjFweG5A+/E7GrDLCc/VOK
                      zBjswUTOwojWqrNSXUccEys6uAa1WsShnkkF7lEAJtTEn1EJX6SshCGvJINAul30
                      BPeaujWS8T8Suyk/U1qjDmTzhFagf+7DMzEfgrDMVVVRE1DlYn/9oeb5AEVFH7Ni
                      503unWNI56lYtaXQXHIZZnHYIfSMPSVehMZiRZ8J+cySgUJ9GhsBfR/Ocvc6l4ra
                      V0523cSusACQ7uV9Eyj62B2P1TYnxFr443/qF0TFXzc2wBcXISflW7RBq+KB+8XV
                      J5IbN70CgYEA8vVBmWcbTp3iKCCBolEQJKKEKn2WEKNlEITnKq/sL419fWFbkaju
                      asxC/OBWhA+lqvgxso9UCi89XKVFbjqQhcuNB3GxhCGmRq9WnJVXqa92tjnKg6FE
                      hLZNjhx448AnK6EshNT3VN+fr2BoqEe2M8Yz7yfyf0m0bx+ZNNdwZD8CgYEAwZyw
                      zaEmIuvKCFnvhf/MRlQhB3aFyAiraiArpL+wnQ6PP1VVazzq5FXI3jZ+nELfhnXU
                      r2tCU9yJVA0buCeACEe0Xw5f98j4YduUedOJpo8hzf0QZtwgFu2ci9M3ndNSiyJO
                      6BzvI4TAOPMyJ/rFXhCWU4sPIAgCn5R9EKU/iZ8CgYEAy3rs/fWEwUsp5kGTUMZj
                      pssVtiCIVlcChdtJYE8GmKz/tMqdTlkVlQyN7gxVaTVRoudLeCjiUcVOtxEUHUWf
                      VO8tplZqPieQgxLGj03kpZD285djLOsb36pvOd5OwTBlnfzWtElI/CRuMQulm4qz
                      5pjRVjM2vbSVEZx9S+xDjTECgYEAl10MzHYD/qEgXc8R90y4QvNarx72ECDXAi0M
                      ccx7Iw5S50yrbx889C4sz60C5t9RKSnNkSblv/JWWqO03A/lhJOqa/YtCObRaI/m
                      UCgVIWYdI5GI1SGa5NH25UnH3Vds3OGBlu2n97i9HsjimWbwDk4heEbrGDuq8V+B

server:
  port: 8888